In [1]:
from reader import Reader
import yaml
from const import Const
import random
import numpy as np
from utils import get_F_example
from clustering import Clusters

In [2]:
reader = Reader()

In [3]:
df = reader.read('input.xlsx')

i
X
X


In [4]:
const = Const()

C:\Users\Jack\PycharmProjects\Clusters\const.py:11: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.config = yaml.load(open("settings.yaml", 'r'))


In [5]:
const.norm(df)

In [6]:
const.calculate_a(df)

In [7]:
const.config

{'conturs': {'min_points': 30,
  'contour_points': 50,
  'min_diff': 0.83,
  'num_of_lenghts': 4},
 'isolated_cluster': {'constU1': 0.05,
  'min_len': 0.97,
  'min_dif': 0.83,
  'divider': 2,
  'max_div_num': 8},
 'knots': {'min_fuses_num': 15, 'stop_const': 0.97},
 'consts': {'round_const': 2,
  'const': 0.25,
  'percent_X': 20,
  'down_steps': 4,
  'up_steps': 6,
  'power_koef': 1.16,
  'percent_Y': 33,
  'threshold': 0.8,
  'Y_step': 2.5,
  'a': 0.9718899463064054}}

In [8]:
X = df.iloc[:].values
F = np.array(get_F_example(X, const.config['consts']['a']))[:,-1]
df['F'] = F
df

id         X1         X2         F
0      1  25.525098  13.422550  0.012962
1      2  26.243550  14.716993  0.015767
2      3  24.977152  15.894720  0.021865
3      4  25.418696  15.946192  0.024346
4      5  26.140631  17.181028  0.026508
..   ...        ...        ...       ...
201  202  54.893922   0.130927  0.047718
202  203  56.727169   1.764082  0.042838
203  204  55.864933   2.653560  0.042566
204  205  55.310172  -0.095715  0.044893
205  206  57.201339   2.319651  0.035988

[206 rows x 4 columns]

In [9]:
cluster = Clusters(const.config)

In [10]:
out_clusters = cluster.get_isolated_clusters(df)

In [17]:
len(out_clusters)

1

In [12]:
out_clusters

[[array([8.30000000e+01, 2.50758878e+01, 2.29982881e+01, 7.82862365e-02]),
  array([1.13000000e+02, 2.50847653e+01, 2.25719154e+01, 7.80617604e-02]),
  array([1.32000000e+02, 2.48142456e+01, 2.23309113e+01, 7.79757259e-02]),
  array([1.86000000e+02, 2.50162666e+01, 2.31336810e+01, 7.77141156e-02]),
  array([28.        , 24.69854921, 22.04413375,  0.07621122]),
  array([29.        , 24.59929005, 21.86262531,  0.07409344]),
  array([1.30000000e+02, 2.46940628e+01, 2.32820041e+01, 7.34654537e-02]),
  array([8.80000000e+01, 2.51254875e+01, 2.36545407e+01, 7.32685929e-02]),
  array([1.34000000e+02, 2.57250097e+01, 2.35027099e+01, 7.28449242e-02]),
  array([8.50000000e+01, 2.55990374e+01, 2.37226868e+01, 7.23115503e-02]),
  array([9.10000000e+01, 2.41497864e+01, 2.26497443e+01, 7.20098014e-02]),
  array([1.89000000e+02, 2.56945773e+01, 2.36923093e+01, 7.16631006e-02]),
  array([30.        , 25.55737451, 21.87867425,  0.06921382]),
  array([1.91000000e+02, 2.44958778e+01, 2.14771953e+01, 6.80

In [13]:
def save_array(data, header, fmt, filename, delimiter=','):
    if filename.endswith('csv') or filename.endswith('txt'):
        np.savetxt(filename, data, fmt=fmt, header=header)

In [15]:
result = []
for i in range(len(out_clusters)):
    for point in out_clusters[i]:
        result.append(np.append(point, i))

header = str(['Id'] + ['X{}'.format(i+1) for i in range(len(result[0])-3)] + ['F'] + ['Cluster_id'])[1:-1]
fmt = str(['%i'] + ['%1.6f' for c in result[0][2:-1]] + ['%1.6f', '%i'])[1:-1].replace("'", '')
out_file = 'output.csv'
save_array(result, header, fmt, out_file)

In [16]:
result

[array([8.30000000e+01, 2.50758878e+01, 2.29982881e+01, 7.82862365e-02,
        0.00000000e+00]),
 array([1.13000000e+02, 2.50847653e+01, 2.25719154e+01, 7.80617604e-02,
        0.00000000e+00]),
 array([1.32000000e+02, 2.48142456e+01, 2.23309113e+01, 7.79757259e-02,
        0.00000000e+00]),
 array([1.86000000e+02, 2.50162666e+01, 2.31336810e+01, 7.77141156e-02,
        0.00000000e+00]),
 array([28.        , 24.69854921, 22.04413375,  0.07621122,  0.        ]),
 array([29.        , 24.59929005, 21.86262531,  0.07409344,  0.        ]),
 array([1.30000000e+02, 2.46940628e+01, 2.32820041e+01, 7.34654537e-02,
        0.00000000e+00]),
 array([8.80000000e+01, 2.51254875e+01, 2.36545407e+01, 7.32685929e-02,
        0.00000000e+00]),
 array([1.34000000e+02, 2.57250097e+01, 2.35027099e+01, 7.28449242e-02,
        0.00000000e+00]),
 array([8.50000000e+01, 2.55990374e+01, 2.37226868e+01, 7.23115503e-02,
        0.00000000e+00]),
 array([9.10000000e+01, 2.41497864e+01, 2.26497443e+01, 7.20098014